In [1]:
import numpy as np

In [2]:
liste = [1, 2, 3, 4]
z = np.array(liste)
z

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4, 5]) # (1 boyutlu dizi : Vektör)

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [6]:
a.ndim # dizi boyutu

1

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
a[2] = 8
a

array([1, 2, 8, 4, 5])

In [9]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # 2. dereceden dizi tanımlama

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b.ndim

2

In [12]:
b.shape # 2 satır, 4 sütun : 2 boyutlu dizi

(2, 4)

In [13]:
print(b[0, 0]) # 0. satır 0. sütundaki eleman

1


In [14]:
print(b[0, 0], b[1, 0], b[1, 1])

1 5 6


In [15]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c.ndim # boyutu..

2

In [18]:
c.shape

(3, 3)

In [19]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
s = np.zeros((2, 2))

In [22]:
s

array([[0., 0.],
       [0., 0.]])

In [23]:
s2 = np.ones((2,3))

In [24]:
s2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
s3 = np.full((3,3), 8)

In [26]:
s3

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [27]:
s4 = np.empty((4, 5))

In [28]:
s4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
print(s4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
s5 = np.eye(4) # 4 * 4 lük birim matris

In [31]:
s5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
s7 = np.arange(5, 60, 3)

In [33]:
s7

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [34]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [35]:
s8 = np.linspace(2, 10, 6) # 2 ile 10 arasında 6 parçaya bölüyor

In [36]:
s8

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [37]:
s6 = np.random.random((5, 5))
#random, 0 ile 1 arasında float değer döndürür

In [38]:
s6

array([[0.76782074, 0.77156284, 0.03898734, 0.80837577, 0.33091529],
       [0.89146858, 0.43103857, 0.72098245, 0.64830984, 0.90122964],
       [0.57304507, 0.46024312, 0.53232955, 0.7841119 , 0.84974972],
       [0.9506198 , 0.49276117, 0.3903593 , 0.31107535, 0.52738205],
       [0.81369738, 0.49700073, 0.36490391, 0.43783793, 0.48224563]])

In [39]:
np.random.randint(0, 100, size = 10)

array([69, 11, 90, 24, 31, 25,  3, 59, 30, 65])

In [40]:
np.random.randint(5, 10, size = (4, 4))

array([[9, 6, 8, 8],
       [8, 5, 7, 6],
       [6, 6, 5, 9],
       [5, 5, 8, 7]])

In [41]:
d2 = np.random.randint(15, 30, size = (5, 3))

In [44]:
print(d2)
print(d2.shape)

[[28 18 20]
 [23 18 17]
 [29 22 27]
 [28 25 16]
 [22 22 16]]
(5, 3)


In [45]:
d2.reshape(3, 5) # yeniden şekillendirmede çarpımları 15 olan bir şekle dönüştürebiliriz..

array([[28, 18, 20, 23, 18],
       [17, 29, 22, 27, 28],
       [25, 16, 22, 22, 16]])

In [46]:
d3 = np.random.randint(3, 13, size = (5,3))

print(d3)
d3.shape

[[ 6  7 11]
 [ 5  6  8]
 [12 12 12]
 [12  7  6]
 [ 4  8  6]]


(5, 3)

In [47]:
d3 = d3.ravel()

#tek bir vektöre dönüştürüyor, uç uca ekleyerek..

print(d3)

[ 6  7 11  5  6  8 12 12 12 12  7  6  4  8  6]


In [48]:
d3.shape

(15,)

In [50]:
d3.dtype

dtype('int32')

In [51]:
d3

array([ 6,  7, 11,  5,  6,  8, 12, 12, 12, 12,  7,  6,  4,  8,  6])

In [52]:
d3.max()

12

In [53]:
d3.min()

4

In [54]:
d3[:: -1]

array([ 6,  8,  4,  6,  7, 12, 12, 12, 12,  8,  6,  5, 11,  7,  6])

In [55]:
yeni = np.random.randint(1, 100, 10)

In [56]:
yeni

array([95, 87, 37, 64, 97, 65, 96, 80,  5, 11])

In [57]:
yeni.min()

5

In [58]:
yeni.max()

97

In [59]:
yeni.argmin()
# minimum olan elemanın index ini verir

8

In [60]:
yeni.argmax()
# maksimum olan elemanın index ini verir

4

In [61]:
yeni.mean()

63.7

In [62]:
yeni.shape

(10,)

In [63]:
np.argmin(yeni)

8

In [64]:
np.argmax(yeni)

4

In [66]:
yeni.sum()

637

In [67]:
yeni.sum()/ 10
#aritmetik ortalamasını aldık..

63.7

In [68]:
d4 = np.random.randint(15, 30, size = (4, 5))
d4

array([[17, 27, 27, 25, 28],
       [25, 20, 19, 27, 17],
       [18, 27, 24, 21, 18],
       [15, 15, 19, 28, 28]])

In [69]:
d4.sum(axis = 0)
# sütunlar(columns) toplanıyor

array([ 75,  89,  89, 101,  91])

In [72]:
d4.sum(axis = 0).reshape(1,5)

array([[ 75,  89,  89, 101,  91]])

In [70]:
d4.sum(axis = 1)
# satırlar(raws) toplanıyor

array([124, 108, 108, 105])

In [71]:
d4.sum(axis = 1).reshape(4, 1)

array([[124],
       [108],
       [108],
       [105]])

In [73]:
d4.mean(axis = 0)

array([18.75, 22.25, 22.25, 25.25, 22.75])